### ISSUE TITLE
[BUG] Type `list[Link]` results in a list of objects in the DB, not a list of `DBRef`s

### ISSUE THREAD

**Issue by efrechette-rga** [BeanieODM/beanie#1009]
Using `list[Link]` as a field type in a document should work exactly the same as `typing.List[Link]`, but it does not. It causes Beanie to save the full linked documents in the DB.

**To Reproduce**
```python
class Child(Document):
    data: str

class Parent(Document):
    children: list[Link[Child]]

child = Child(data="hello")
child.insert()

parent = Parent(children=[child])
parent.insert()
```

In the DB, the parent collection looks like
```
_id: ObjectID(...)
children: Array (1)
  0: Object
    _id: ObjectID(...)
    data: "hello"
```

Instead, it should look like
```
_id: ObjectID(...)
children: Array (1)
  0: DBRef(...)
```

**Expected behavior**
`list[Link]` types should work exactly like `typing.List[Link]` which results in a list of `DBRef`s in the DB, not a list of objects.

**Comment by staticxterm** [comment]
Hi @efrechette-rga, please note that I am not an authority on anything Beanie related.

I am not able to reproduce your problem on Beanie 1.26.0 and using Pydantic 1.10.18 or Pydantic 2.8.2.
Please provide a full reproducible example.

I don't think the problem is with the typing of the 'children' attribute being 'list[Link[Child]]' versus 'typing.List[Link[Child]]'.
Also, both 'list[Link]' and 'typing.List[Link]' are not valid as types for the _Parent_ class 'children' attribute due to Generic typing of the _Link_ class.

As a "workaround" to your problem, you may want to use either one of the below two approaches.

You can call the .to_ref() method on the Child instance:
```python
    parent = Parent(children=[child.to_ref()])
    result = await parent.insert()
```
Beanie also supports another pattern where your don't first insert the Child document but write it all from the Parent one, for example:
```python
    child = Child(data="hello")
    parent = Parent(children=[child])
    result = await parent.insert(link_rule=WriteRules.WRITE)
```
