### ISSUE TITLE
[BUG] - Beanie migrations run throws no module named 'some_document'

### ISSUE THREAD

**Issue by danielxpander** [BeanieODM/beanie#992]
**Describe the bug**
I tried running a migration that follows the [guideline](https://beanie-odm.dev/tutorial/migrations/) but when i run the migration it fails.
I tried putting it in various directory levels(I'm using fastapi so i tried in root, src, inside the package holding the document i want to import and run the migration against).

**To Reproduce**
```python
beanie migrate -uri 'mongodb://user:pwd@localhost:27017' -db 'some_db' -p src/models/primary --distance 1 --no-use-transaction
As well as
beanie migrate -uri 'mongodb://user:pwd@localhost:27017/some_db' -p src/models/primary --distance 1 --no-use-transaction
```

**Expected behavior**
Run the migration with no errors

**Additional context**

**Comment by alex-pythonista** [comment]
hey @danielxpander thanks for mentioning this issue here. I faced the name error while importing documents from `models` directory. I submitted a stackoverflow question here: https://stackoverflow.com/questions/78936569/beanie-migrate-command-throwing-modulenotfounderror-even-though-i-put-init-p
Hope this helps.
cc: @roman-right @07pepa
